DROP TABLE VEHICLE IF EXISTS;

CREATE TABLE VEHICLE (ID bigint identity primary key, VIN varchar(255), BOJA varchar(255), BROJ_OSOVINA integer, IDENC integer,
                      NACIN_NAPLATE VARCHAR(255), REGISTRACIJSKA_OZNAKA VARCHAR(255), DRZAVA_REGISTRACIJE VARCHAR(255),
                      EKO_RAZRED VARCHAR(255), KATEGORIJA VARCHAR(255), OZNAKA_AUTOCESTE VARCHAR(10),
                      POCETNA_DIONICA_OZNAKA VARCHAR(255), POCETNA_DIONICA_ID integer,
                      ZAVRSNA_DIONICA_OZNAKA VARCHAR(255), ZAVRSNA_DIONICA_ID integer,
                      PROSJECNA_BRZINA float);